seed: 42                                  # Define the random seed for consistent results.
mlflow: false                             # Switch to turn on/off mlflow for experiment tracking.
profile: false                            # If True, it will profile runtime of each step from main() onwards.   
paths:                                    #
    data: ./data/                         # Where the data is stored.
    results: ./results/                   # Where the results such as trained model, and plots will be saved.                          #
model_config: ae                          # If there are multiple model config files, define which one to use.
